### ISSUE TITLE
COVID-19: what is the right workflow for producing VCF file?

### ISSUE THREAD

**Issue by adily777** [broadinstitute/viral-pipelines#192]
Hello,

I have some COVID-19 fastq files. I would like to run them (on DNAnexus) by workflow that create a snp list - VCF file.

I see there are many viral-ngs worflows. 
Which of them is appropriate for my input (fastq) and desired output (vcf)? 
Should I run several worflows?

Hope for quick answer,
Thank you in advance,

Adily

**Comment by tomkinsc** [comment]
Hi Adily, 

The majority of our pipelines are set up to accept input data in unaligned bam format (which maintains a breadcrumb trail of history in the header and read-specific tags, etc.). To start you can use the [`fastq_to_ubam`](https://github.com/broadinstitute/viral-pipelines/blob/master/pipes/WDL/workflows/fastq_to_ubam.wdl) workflow to convert your fastq files to bam format. From there you can run [`assemble_refbased`](https://github.com/broadinstitute/viral-pipelines/blob/master/pipes/WDL/workflows/assemble_refbased.wdl) which will map the reads to the reference (must provide the SARS-CoV-2 [reference](https://www.ncbi.nlm.nih.gov/nuccore/NC_045512.2) in fasta format) to assemble a genome and also output a VCF file with SNPs and indels as called by GATK (the VCF is the `align_to_ref_variants_vcf_gz ` output). In general, the process aligns reads with Novoalign, removes PCR duplicates with Picard (in order to debias the allele counts in the pileups), and realigns reads with GATK's IndelRealigner (in order to call indels).

For genomes you have already assembled, if you only need SNP calls, you can run [`mafft_and_snps`](https://github.com/broadinstitute/viral-pipelines/blob/0d5a361beb4841721cc5cd78cb7a151bd6a69349/pipes/WDL/workflows/mafft_and_snp.wdl), which will quickly map genomes to the reference using MAFFT, then call SNPs via [`snp-sites`](https://sanger-pathogens.github.io/snp-sites/). 

I'm going to close this issue, but feel free to reopen if you have questions or encounter any problems.

Chris
